server:
  port: 8084
spring:
  application:
    name: shop-service
---
spring:
  rabbitmq:
    host: 47.107.232.63
    port: 5672
    username: admin
    password: admin
---
eureka:
  client:
#    healthcheck:
#      enabled: true
    service-url:
      defaultZone: http://localhost:8000/eureka/
    fetch-registry: true
    register-with-eureka: true
  status:
    open: true

