server:
  port: 8080
spring:
  application:
    name: zuul-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/
zuul:
  routes:
    shop-service:
      path: /shop/**
      serviceId: SHOP-SERVICE
    user-service:
      path: /user/**
      serviceId: USER-SERVICE
